version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        CUDA_VERSION: 12.4
    image: hotwa/lilly_mol:test
    container_name: lilly_mol
    volumes:
      - ../test:/LillyMol/test
    command: >
      bash -c "tail -f /dev/null"
